# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"

  # ----------------------------first machine--------------------------------#
    config.vm.define "xuwangS" do |master| 
      master.vm.hostname = "xuwangS"
      master.vm.network "private_network", ip: "192.168.56.110"
      master.vm.provider "virtualbox" do |vb|
        vb.name = "xuwangS"
        vb.memory = "1024"
        vb.cpus = 1
      end
      # master.vm.privision "shell", inline: <<-SHELL

      # SHELL
    end
  # ----------------------------second machine--------------------------------#
    config.vm.define "xuwangSW" do |woker| 
      woker.vm.hostname = "xuwangSW"
      woker.vm.network "private_network", ip: "192.168.56.111"
      woker.vm.provider "virtualbox" do |vb|
        vb.name = "xuwangSW"
        vb.memory = "1024"
        vb.cpus = 1
      end
      # woker.vm.privision "shell", inline: <<-SHELL
      
      # SHELL
    end
end

  
