# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version {we support older styles for
# backwards compatibility}. Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
    config.vm.box = "centos/7"
  # ----------------------------first machine--------------------------------#
  # config.vm.define "web" do |web|
  #   web.vm.network "private_network", ip: "192.168.33.11"
  # end
    config.vm.define "xuwangS" do |master| 
      master.vm.hostname = "xuwangS"
      master.vm.network "private_network", ip: "192.168.56.110"
      master.vm.provider "virtualbox" do |v|
        v.name = "xuwangS"
        v.memory = 1024
        v.cpus = 1
      end
      master.vm.provision "shell", inline: <<-SHELL
      curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" INSTALL_K3S_EXEC="server" sh -s - 
      echo $(sudo cat /var/lib/rancher/k3s/server/node-token) > /vagrant/token
      SHELL
    end
    

  # ----------------------------second machine--------------------------------#
   
    config.vm.define "xuwangSW" do |worker| 
      worker.vm.hostname = "xuwangSW"
      worker.vm.network "private_network", ip: "192.168.56.111"
      worker.vm.provider "virtualbox" do |v|
        v.name = "xuwangSW"
        v.memory = 1024
        v.cpus = 1
      end
      worker.vm.provision "shell", inline: <<-SHELL
      curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" K3D_URL=https://192.168.56.110:6443 K3S_TOKEN=$(cat /vagrant/token) INSTALL_K3S_EXEC="server" sh -s -
      SHELL
    end

end