# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
    config.vm.box = "centos/7"
  # ----------------------------first machine--------------------------------#
  # config.vm.define "web" do |web|
  #   web.vm.network "private_network", ip: "192.168.33.11"
  # end
    config.vm.define "xuwangS" do |master| 
      master.vm.hostname = "xuwangS"
      master.vm.network "private_network", ip: "192.168.56.110"
      master.vm.provider "virtualbox" do |v|
        v.name = "xuwangS"
        v.memory = 1024
        v.cpus = 1
      end
    end
    
  # ----------------------------second machine--------------------------------#
   
    config.vm.define "xuwangSW" do |agent| 
      agent.vm.hostname = "xuwangSW"
      agent.vm.network "private_network", ip: "192.168.56.111"
      agent.vm.provider "virtualbox" do |v|
        v.name = "xuwangSW"
        v.memory = 1024
        v.cpus = 1
      end
    end

end
